### ISSUE TITLE
issues with <redirect />

### ISSUE THREAD

**Issue by PaulKujawa** [single-spa/single-spa-layout#116] opened 2021-02-08 13:44 UTC
There seem to be some issues with the `redirect` functionality:

* It seems to be order-sensitive so that one needs to put it after other routes
* when a redirect happened, the content is centred
* it does not redirect from the base url (`/` or in the demo app `/next[/]`)
* the format is not clear as the [react-demo](https://github.com/react-microfrontends/root-config/blob/cb354277ecfb142267810c2636c4e964048c8edb/src/index.ejs#L34) is different from the [test fixtures](https://github.com/single-spa/single-spa-layout/blob/47724c9546106f9780804b613cebf9a31c7c2204/test/fixtures/redirects.html#L10).

This is a small reproduction app https://github.com/PaulKujawa/issue-single-spa-redirect and there was also a [Slack conversation](https://single-spa.slack.com/archives/C8R6U7MT7/p1611936732159100) leading to this Github issue.

**Comment by joeldenning** [comment] 2021-02-08 18:00
Hi Paul, thanks for creating the issue with a demonstration repo. Going through the bugs listed in the readme, one by one:

> Commit adc62576fdb96fe5c250403017a30b91002f4ddd Redirect from /fruits works but the page is now blank.

At that commit, there are no redirects in the layout definition. I think this was just a mistake when you created the issue, and am happy to investigate if you point me to a commit that shows it. See https://github.com/PaulKujawa/issue-single-spa-redirect/blob/adc62576fdb96fe5c250403017a30b91002f4ddd/root-config/src/index.ejs#L76.

> Commit 223cba4f43e95c87005088e73feb9b85c9b258b4 Putting the redirect after routes fixes the apps, but the content is strangly centered on the page on redirect.

The commit hash listed here is wrong, but the link is correct. The reason that the content is centered is because the single-spa-welcome application adds some CSS to the `<body>` element. When you go to veggies it's loading the css for single-spa-welcome, since single-spa-welcome is the default route, before it redirects to fruits. See https://github.com/single-spa/create-single-spa/blob/7facc4e51ea124a7cbb1c8c085da2bf3d5bf8e33/packages/single-spa-welcome/src/welcome.css#L1

> It seems to be order-sensitive so that one needs to put it after other routes

This was not shown in any of the commits in the readme of the demonstration repo.

> when a redirect happened, the content is centred

This was explained above

> it does not redirect from the base url (/ or in the demo app /next[/])

This was not shown in any of the commits in the readme of the demonstration repo.

> the format is not clear as the react-demo is different from the test fixtures.

Leading slashes are optional in redirects. I've clarified this in the documentation with https://github.com/single-spa/single-spa.js.org/pull/407

**Comment by joeldenning** [comment] 2021-02-08 18:12
I've also created https://github.com/single-spa/create-single-spa/pull/259 which scopes the css of single-spa-welcome so that others don't experience the same confusion about the global css contained there. Generally, single-spa-welcome shouldn't be used after initial creation of the root config, but it was an easy enough fix.

**Comment by PaulKujawa** [comment] 2021-02-08 20:44
To avoid further confusion I've created branches.

* [redirect-overrides](https://github.com/PaulKujawa/issue-single-spa-redirect/tree/redirect-overrides) when you open /veggies you should get to /fruits but you see the default page.
* [order-sensitivity](https://github.com/PaulKujawa/issue-single-spa-redirect/tree/order-sensitivity) when you open /fruits you should see the fruits app but see a blank page.
* [redirect-root](https://github.com/PaulKujawa/issue-single-spa-redirect/tree/redirect-root) well, this turned out to be on our side. I assume that our ingress or nginx is wrongly configured so that it always redirects with a trailing slash. So `/prefix/` in this case. Then the redirect of `/prefix` is not triggered. It's understandable that this behaves expected from single-spa's view :)

**Comment by joeldenning** [comment] 2021-02-09 18:20
> redirect-overrides when you open /veggies you should get to /fruits but you see the default page.

This is caused by using self-closing tags. HTML does not allow for self closing tags of arbitrary elements - once you switch to a full closing tag it works:

```diff
- <redirect from="/veggies/foo" to="/foo" />
- <redirect from="/veggies" to="/fruits" />
+ <redirect from="/veggies/foo" to="/foo"></redirect>
+ <redirect from="/veggies" to="/fruits"></redirect>
```

> order-sensitivity when you open /fruits you should see the fruits app but see a blank page.

Same here, switching away from self-closing `<redirect>` tags fixes this.

The problem is that the browser's DOM parser keeps waiting for the `<redirect>` element to close after the self closing tag, so it swallows / doesn't parse elements immediately afterwards.

**Closed by joeldenning** 2021-02-09 18:20 UTC
