### ISSUE TITLE
Single-SPA app no longer rendered when url changes in 1.4.0

### ISSUE THREAD

**Issue by gjhommersom** [single-spa/single-spa-layout#115] opened 2021-02-08 12:16 UTC
I was doing a routine update of packages when I noticed that applications were no longer rendered when the url changes. 

**Short summary**: 
I'm on an url like `/operator/myapp` and navigate to `/configurator/myapp`. This should show the same app (but with different content) but the app seems to be unloaded.

**Configuration**
single-spa: 5.9.1
single-spa-layout: 1.4.0 fails
single-spa-layout: 1.3.1 works

**Layout**
```
<route path="operator">
  <application name="operatorapp">
  <route path="myapp">
    <application name="myapp">
  </route>
</route>
<route path="configurator>
  <application name="configuratorapp">
  <route path="myapp">
    <application name="myapp">
  </route>
</route>
```

**Steps to reproduce**
* Open the website
* Click navigation link to different url
The application is not rendered. Div element with application id exists. It has no child elements.

* Click back in the browser
The application is now rendered on half the screen. There are 2 div elements with the same application id. Only of them has child elements.

![image](https://user-images.githubusercontent.com/28047460/107212925-f6a11800-6a07-11eb-8f6f-714b2512dfa0.png)

**Other information**
There is no output of any kind in the console output. Refreshing the page resolves rendering issues that might have occurred.

**Comment by joeldenning** [comment] 2021-02-08 17:34
single-spa-layout@1.4.0 had some pretty big refactoring, so it's possible there's a bug. Could you please provide a demonstration of the issue, so I can look into it?

**Comment by gjhommersom** [comment] 2021-02-09 09:25
I have created a repository that recreates the problem here: https://github.com/gjhommersom/single-spa-layout-example

While I was doing so I discovered that it doesn't happen for all configurations. Initially it wasn't broken until I accurately used the same config as we have for production. Check the commit for details: https://github.com/gjhommersom/single-spa-layout-example/commit/15ac7323c8278ecf6da427445e7aa6e51a39beed

To run the example:
* Run `yarn` and `yarn start` for the root config and the react app
* Open http://localhost:9900/operator/myapp

You should now be able to reproduce the issue by clicking the link twice.

**Comment by joeldenning** [comment] 2021-02-09 18:41
Thanks for providing a demonstration repo, I've confirmed that it's a regression caused by https://github.com/single-spa/single-spa-layout/pull/112. In single-spa-layout@1.3.0, the `<div id="single-spa-application:@gh/react-app"></div>` would be **moved** before its parent `<div>` was removed from the dom. But in single-spa-layout@1.4.0, the `<div id="single-spa-application:@gh/react-app"></div>` is removed from the because its parent div is being removed before there's a chance to move it to its new container.

I think I'll have time this afternoon to work on a fix for this.

**Comment by joeldenning** [comment] 2021-02-09 23:33
I've created a fix for this at #117. Hope to merge and release a patch in the next day or so.

**Closed** 2021-02-10 18:17 UTC

**Comment by joeldenning** [comment] 2021-02-10 18:19
The fix is released in https://github.com/single-spa/single-spa-layout/releases/tag/v1.4.1. Could you try upgrading to 1.4.1 and see if that works for you? I confirmed it does work in the demonstration repo you provided

**Comment by gjhommersom** [comment] 2021-02-10 19:45
I can confirm that this has solved the issue in production code as well.
