### ISSUE TITLE
single-spa errors being swallowed

### ISSUE THREAD

**Issue by filoxo** [single-spa/single-spa-layout#88] opened 2020-10-28 15:37 UTC
I'm putting together an example and observed that single-spa errors are being swallowed when using single-spa-layout. 

## Steps to reproduce

- clone repo at this commit https://github.com/filoxo/single-spa-example-rxjs-shared-state/commit/f7242c7253f825d7d2fac706baf23e594c4f3f9b
- follow the setup instructions in README to start running locally
- navigate to http://localhost:9000/ and inspect the console. There are no errors.
- edit root-config/src/example-root-config.js and comment out the single-spa-layout code and replace with registerApplication equivalents (below)

      registerApplication({
        name: "@example/navbar",
        app: () =>
          System.import("@example/navbar"),
        activeWhen: ["/"],
      });

      registerApplication({
        name: "@example/home",
        app: () =>
          System.import("@example/home"),
        activeWhen: ["/home"],
      })

      registerApplication({
        name: "@example/login",
        app: () =>
          System.import("@example/login"),
        activeWhen: ["/login"],
      })

- go back to page and inspect the console. single-spa errors are being shown

## Current behavior

What's happening is that the home and login applications are dying with a status of `LOAD ERROR` (visible in the single-spa inspector) but there are no console errors. I switched to using the registerApplication API and then started seeing the error message that explained what is happening (systemjs cannot resolve the bare specifier that these applications require). 

![Screen Shot 2020-10-28 at 9 14 37 AM](https://user-images.githubusercontent.com/4202993/97457428-5a8f4d00-18ff-11eb-97ce-7f7d8025f566.png)
I understand what I need to do to fix the error itself, but it was very confusing/frustrating that I wasn't seeing those error messages when using single-spa-layout. 

## Expected behavior

I would expect that if a single-spa error occurs that that error would be surfaced the same way as if using the registerApplication API.

**Comment by joeldenning** [comment] 2020-10-28 18:33
This sounds like something that should be fixed.

The installation didn't work for me, though. 1I'm using yarn@1.22 and I suspect the project may require yarn 2? I was able to get it working by running yarn install in each folder, though.

Once I ran the projects, the home application mounted successfully both when using single-spa-layout and when not using single-spa-layout.

![image](https://user-images.githubusercontent.com/5524384/97480897-a64ef000-1919-11eb-9977-1ed894bfa30f.png)

**Comment by joeldenning** [comment] 2020-10-28 18:35
If I forcibly cause the home app to not load, by changing its url to one that doesn't exist, then I'm able to reproduce the problem.

**Comment by joeldenning** [comment] 2020-10-28 18:41
I think the reason that I wasn't able to reproduce it at first was that I didn't check out the proper commit.

**Closed** 2020-10-28 19:55 UTC

**Comment by joeldenning** [comment] 2020-10-28 19:57
Fixed in https://github.com/single-spa/single-spa-layout/releases/tag/v1.1.4. Thanks for reporting and providing a demonstration - that made it much easier.

**Comment by filoxo** [comment] 2020-10-28 20:22
👏  nice!
