### ISSUE TITLE
Export WithLoadFunction type

### ISSUE THREAD

**Issue by RafaRochaS91** [single-spa/single-spa-layout#55] opened 2020-07-22 15:06 UTC
* When trying to customise an `ActivityFunction` by iterating over the result of the `constructApplications` I want to be able to (while using strict `Typescript` rules) to type the elements of the resulting array.

**Comment by joeldenning** [comment] 2020-07-22 17:01
Hi @RafaRochaS91, customizing the activity functions created by single-spa-layout might result in unexpected behavior, since the layout engine will not know where to place the application when it detects that it's about to be mounted. What is the reason you want to modify the activity functions?

Regarding the WithLoadFunction type, the return value of `constructApplications` is `RegisterApplicationConfig`, which is exported from single-spa. The WithLoadFunction that gets merged into it just makes it slightly more specific about the `app` property being a function instead of a function or object. I would suggest just using RegisterApplicationConfig from single-spa:

```ts
import { RegisterApplicationConfig } from 'single-spa';
import { constructApplications } from 'single-spa-layout';

const applications: RegisterApplicationConfig[] = constructApplications(...)
```

^ I believe that the above will work, since the return value of constructApplications matches the type for RegisterApplicationConfig

**Comment by RafaRochaS91** [comment] 2020-07-23 13:53
```ts
  const applications = constructApplications({
    loadApp: async ({ name }: { readonly name: string }) => System.import(name),
    routes,
  }).map(
    (
      application: RegisterApplicationConfig<Record<string, unknown>> &
        WithLoadFunction
    ) => {
      if (application.name === '@somecompany/microfrontend') {
        return {
          ...application,
          activeWhen: (): boolean => getAuthState() !== null,
        };
      }

      return application;
    }
  );
```

The above one works but we need to import `WithLoadFunction` like so:
```ts
import { WithLoadFunction } from 'single-spa-layout/dist/types/constructApplications';
```

If I follow your suggestion then it complains when I pass the `applications` variable to the `constructLayoutEngine` function.

**Comment by joeldenning** [comment] 2020-07-23 16:36
I see. I'm open to the change, then. We're using jsdoc syntax for the types, so I'm not sure how to export it from the main file. I'll look into it.

**Comment by joeldenning** [comment] 2020-07-23 16:49
I've put together a fix at #56 - will plan on publishing after it's reviewed and merged.

**Comment by RafaRochaS91** [comment] 2020-07-24 05:21
Thank you! It's really handy 👍

**Comment by joeldenning** [comment] 2020-07-24 16:57
Published in https://github.com/single-spa/single-spa-layout/releases/tag/v1.0.0-beta.6

**Closed by joeldenning** 2020-07-24 16:57 UTC
