### ISSUE TITLE
Cannot read property 'meta' of undefined     at autoPublicPath when loading MFE created with create-single-spa using Single-Spa-layout RootConfig build with Custom Webpack5 

### ISSUE THREAD

**Issue by ajasingh** [single-spa/single-spa-layout#128] opened 2021-04-29 13:58 UTC
We are getting below exception while loading a MFE created with create-single-spa CLI 
Uncaught TypeError: application '@test/test' died in status LOADING_SOURCE_CODE: Cannot read property 'meta' of undefined
    at autoPublicPath (auto-public-path.js:15)
    at Object../node_modules/systemjs-webpack-interop/auto-public-path/1.js (1.js:3)
    at __webpack_require__ (bootstrap:24)
    at startup:6
    at Object.execute (startup:7)
    at i (system-core.js:279)
    at e (system-core.js:275)
    at system-core.js:232

Root-Config-Webpack

const path = require('path');
const CleanWebpackPlugin = require('clean-webpack-plugin').CleanWebpackPlugin;

```
module.exports = {
	entry: path.resolve(process.cwd(), 'src/console-root-config.js'),
	target: ['web', 'es5'],
	output: {
		path: path.resolve(process.cwd(), 'dist'),
		libraryTarget: 'system',
		filename: 'bundle.js',
		uniqueName: 'console_rootconfig',
		publicPath: '',
	},
	module: {
		rules: [
			{
				test: /\.(js|jsx)$/,
				exclude: [/node_modules/],
				use: ['babel-loader'],
			},
		],
	},
	externals: ['single-spa', 'react', 'react-dom', 'moment', 'styled-components', 'lodash', /^@console\/.*/],
	plugins: [new CleanWebpackPlugin()],
};
```

```
const applications = constructApplications({
			routes,
			loadApp({ name }) {
				if (name === '@console/middleware') {
					return Promise.resolve(middlewareApp);
				} else {
					return System.import(name);
				}
			},
		});
		const layoutEngine = constructLayoutEngine({ routes, applications, active: false });
```

```
<route path="test/test">
--
  | <application name="@test/test" loader="commonLoader" error="layoutError" props="getFeatureFlags,getUserProfile,getLocale,executionContext,getProductContext,getServerConfig,appConfig"></application>
  | </route>
```

**Comment by joeldenning** [comment] 2021-04-29 22:12
This error occurs if you're using webpack 4 or your webpack config's `output.libraryTarget` is not set to `"system"`. It is likely not related to single-spa-layout. See https://github.com/joeldenning/systemjs-webpack-interop for documentation.

Closing this since I think the above explanation is the root cause, but feel free to reopen or comment further (or create issue in systemjs-webpack-interop) if it persists.

**Closed by joeldenning** 2021-04-29 22:12 UTC

**Comment by joeldenning** [comment] 2021-06-03 16:14
A client I work with saw this problem today, and it ended up being related to [this custom systemjs extra](https://github.com/react-microfrontends/api/issues/1#issuecomment-594289086). SystemJS checks the function length (number of arguments) of the registration function, and that custom extra changed the function length accidentally.

I have modified the extra in that Github comment, but also am posting the corrected extra here in case it's helpful for people:

```
<script>
  (function() {
    const originalInstantiate = System.constructor.prototype.instantiate;
    System.constructor.prototype.instantiate = function() {
      return originalInstantiate
        .apply(this, arguments)
        .then(function(register) {
          const originalFn = register[1];
          register[1] = function(_export, _context) {
            _export("__esModule", true);
            return originalFn.call(this, _export, _context);
          };
          return register;
        });
    };
  })();
</script>
```
