### ISSUE TITLE
Loading UI is not working

### ISSUE THREAD

**Issue by kush1995ptl** [single-spa/single-spa-layout#84] opened 2020-10-26 03:58 UTC
Hi, loading UI is not working. I did same code provided in single spa layout documentation. I have attached screenshot for the same. It it giving the error app died.

<img width="643" alt="problem1" src="https://user-images.githubusercontent.com/26465600/97132599-7a8f0700-176d-11eb-8428-f9a432d6fbfc.png">
<img width="606" alt="problem2" src="https://user-images.githubusercontent.com/26465600/97132603-7cf16100-176d-11eb-9ff6-bcca6a51e0be.png">
<img width="959" alt="problem3" src="https://user-images.githubusercontent.com/26465600/97132606-7f53bb00-176d-11eb-8448-26841d159c8c.png">

**Comment by joeldenning** [comment] 2020-10-26 16:36
Hi @kush1995ptl, I tried out loading states in the react-microfrontends example and was unable to reproduce this issue. The loading UIs showed when the navbar failed to load, and when it loaded.

Could you confirm that you're using the latest version of single-spa-layout in your root config? The latest is 1.1.2: https://github.com/single-spa/single-spa-layout/releases/tag/v1.1.2

**Comment by joeldenning** [comment] 2020-10-26 16:38
Also, you can see loading states working by going to https://react.microfrontends.app/ and throttling your network connection in the chrome devtools so that the loading state stays around longer.

One thing to note is that it is expected and normal for loading UIs to disappear when an application fails to load. If you're wanting to show a UI when the application fails to load and mount, you should use Error UIs instead of loading UIs. See https://single-spa.js.org/docs/layout-definition#error-uis

**Comment by joeldenning** [comment] 2020-10-26 16:45
I'm closing this issue since I think that this is likely a misunderstanding of the behavior of Loading UIs (that they disappear after the application fails to load). Feel free to comment further or reopen.

**Closed by joeldenning** 2020-10-26 16:45 UTC
